### ISSUE TITLE
NSFW Repository 

### ISSUE THREAD

**Issue by Alanray64** [TheNetsky/extensions-sources#1]
Consistently gives error. Uninstalled and reinstalled numerous times. Cloudfare bypass works when used however unable to use in the library section. (V0.7 r30)
![A0485620-98AF-4B64-A98F-48A0896E3C36](https://user-images.githubusercontent.com/78024015/165240707-7f7e9d13-60ca-4b1f-9c70-66b5ba20fbd8.jpeg)

**Comment by TheNetsky** [comment]
Unrelated to any of the sources.
