### ISSUE TITLE
NHentai Search Issue

### ISSUE THREAD

**Issue by juispr** [TheNetsky/extensions-sources#13]
![B5E42395-5235-4B86-B352-D5E778A3BC7C](https://user-images.githubusercontent.com/107940155/174831790-9ad24224-7bae-432e-baf5-ce763fe2563c.jpeg)
Any search I do returns this error code.
v0.7-r46
NHentai NotMarek 3.2.2

**Comment by TheNetsky** [comment]
See Discord source status.
