### ISSUE TITLE
Mangakakalot stopped working

### ISSUE THREAD

**Issue by koiinnano** [TheNetsky/extensions-sources#16]
![FBC2B568-5BFA-410C-A144-F0D3A0F281C7](https://user-images.githubusercontent.com/108392667/176379279-b0c16267-4698-4187-863d-245f9762a93e.png)

**Comment by TheNetsky** [comment]
Please check the website before opening an issue thanks, it's clearly down.

**Comment by koiinnano** [comment]
sorry my browser was showing a snap shot so it looks like it was still running.
