### ISSUE TITLE
Reaper scans not working 

### ISSUE THREAD

**Issue by Sahibs1** [TheNetsky/extensions-sources#18]
Reaper scans is not refreshing in the library and The homepage is not working. There is nothing showing up and I keep getting an error. 
![5FD6B655-C441-46C8-B7BA-89869E1636AD](https://user-images.githubusercontent.com/108420410/176726284-6c17e2ce-b510-454e-87f7-4ef816ddc89d.png)
![9195EEBD-5956-4F2C-93AE-9C40616103C5](https://user-images.githubusercontent.com/108420410/176726287-4b45db9e-d1f4-4186-9ac1-b1d6afb92d03.png)

**Comment by TheNetsky** [comment]
Just mean website is slow or your network is.
