### ISSUE TITLE
AsuraScans update time different

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/extensions-sources#21]
The manhwa update time in the 'Discover' section is in minutes/hours, however in the 'Library' it always shows more than 20 hours

### Example 1:
Update time in '_Discover_' page for 'Return of the 8th Class Magician' is **15 minutes**, but in the _'library' / manhwa 'info'_ it is **22 hr**
![1 - Discover page](https://user-images.githubusercontent.com/89789474/177043546-db27c797-138e-4ca8-a4ce-6822dac4284c.PNG)
![2 - Return of the 8th Class Magician](https://user-images.githubusercontent.com/89789474/177043619-9a017201-6aa6-417f-85d1-c744dddd39ad.PNG)

<hr/>

### Example 2:
Update time in '_Discover_' page for 'Legend of Asura' is **2 hours**, but in the _'library' / manhwa 'info'_ it is **22 hr**
![1 - Discover page](https://user-images.githubusercontent.com/89789474/177043546-db27c797-138e-4ca8-a4ce-6822dac4284c.PNG)
![3 - Legend of Asura](https://user-images.githubusercontent.com/89789474/177043660-e35373bf-554d-4ac2-b345-c438ec7c59bb.PNG)

**Comment by TheNetsky** [comment]
That's because on the homepage it returns exact time in minutes, on the chapter listing just the current date.
