### ISSUE TITLE
[BUG] nhentai source stuck on cloudflare check

### ISSUE THREAD

**Issue by smurfkb** [TheNetsky/extensions-sources#24]
**Describe the bug**
When trying to bypass cloudflare, the webview stays on the “checking your browser” screen indefinitely.

**To Reproduce**
1. Go to source settings for nhentai
2. Click on 'Cloudflare Bypass'

**Expected behavior**
Waiting 5 seconds or so and getting redirected to the nhentai homepage.

**Screenshots/Video**
https://streamable.com/0yyqe2

**App version**
- v0.7-r46

**Source WITH source version**
- nhentai 3.2.3

**Comment by TheNetsky** [comment]
Some people seem to have issues with Cloudflare (again). However personally it's working fine for me.
