### ISSUE TITLE
AsuraScans not working

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/extensions-sources#27]
**Describe the bug**
No images are displayed in AsuraScans, saved manhwas/ chapter markers also missing

Cloudflare bypass still shows website.

Tried restarting the app, deleting the sources and reinstalling it but the error still happens.

**To Reproduce**
1. Go to 'Discovery'
2. Click on 'AsuraScans'
3. See error

**Expected behavior**
All manhwa and images to show.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/89789474/178525271-8e5dc3b3-ccb0-4c55-9a38-fe0b0274eb0b.png)

**App version**
- v0.7-r45

**Source WITH source version**
- AsuraScans 2.1.7

**Comment by chailjc** [comment]
Images also not appearing in 2.1.8 version of AsuraScans.

![image](https://user-images.githubusercontent.com/89789474/178540002-717ae95d-a333-4707-9af8-e78b1fc6db62.png)

No error message pops up in 'Discovery', but in when refreshing for updates in 'Library' this shows up.

![image](https://user-images.githubusercontent.com/89789474/178540225-71183cab-bcc9-47ff-af4d-91bcb38d8946.png)

**Comment by TheNetsky** [comment]
Sorry buddy, this is something on your end.
Works fine for me.
