### ISSUE TITLE
[BUG] "Wayne family adventures" not loading in Webtoons extension

### ISSUE THREAD

**Issue by syekohh** [TheNetsky/extensions-sources#32]
Opening "Wayne family adventures" in the webtoons extension gives this error pop-up: 
"Webtoons: RequestError 
[PaperbackError(301)]
RequestError: Could not create a valid URLSession"

**To Reproduce**
1. Search for "Wayne family adventures"
2. Click on the Webtoon that shows up in the Webtoons extension
3. See error

**Expected behavior**
Expected to display 51 chapters of the webtoon

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/54860722/184573227-689ff6e2-5e6f-4349-a4cc-603d1a5cbccf.png)

**App version**
- v0.7-r46

**Source WITH source version**
- Webtoons 2.1.2

**Additional context**
This webtoon seems to load when using a similar app, with what I believe to be the same extension. I can provide more details with the other app if needed

**Comment by TheNetsky** [comment]
@btylerh7

**Comment by btylerh7** [comment]
Sorry for the delay. Should be an easy fix.
