### ISSUE TITLE
Issue with MangaDex on new Beta update

### ISSUE THREAD

**Issue by Lyndis8** [TheNetsky/extensions-sources#34]
The Beta just updated from r45 to r47 (with the public version being r46). Seeing this, I decided to start using the Beta again because I was getting frustrated with no notifications from MangaDex on the public version from the well-known bug there. The Beta automatically updated to r47 and, when I imported my backup from my public app (r46), MD notifications stopped working on the Beta app (r47). I have been testing it to try to get the notifications to appear, but it does not work whether I refresh or directly access manga with recent chapters uploaded to MD.

I am not sure if this was because backups can't be shared between versions without issues or what. 
If there is no way to fix this, then this post is a heads up that MD notifications don't work on any version of the app right now.

Version: v0.7-r47
IOS: 15.6.1

**Comment by TheNetsky** [comment]
App issue.
