### ISSUE TITLE
[BUG] Can't search/add comics containing an apostrophe.

### ISSUE THREAD

**Issue by AnalogCyan** [TheNetsky/extensions-sources#36]
**Describe the bug**
When searching in Webtoons, attempting to search for or add any comics containing an apostrophe (`'`) results in either an error in the case of searching, or a blank entry in the case of adding/viewing. Attached are screenshots showing this in action.

**To Reproduce**
1. Ensure you have the Webtoon source.
2. Go to search and select Webtoons.
3. Search for any comic with an apostrophe in its name.
4. See error.

**Expected behavior**
The ability to search for, add, and read comics containing apostrophes.

**Screenshots/Video**
![IMG_0863](https://user-images.githubusercontent.com/5077450/195219640-55b914c8-2834-4fee-8061-80b2e34491ef.PNG)
![IMG_0864](https://user-images.githubusercontent.com/5077450/195219652-2955223a-3fd5-4c28-88dc-bcdc8333664f.PNG)

**App version**
- v0.7-r46

**Source WITH source version**
- Webtoons 2.1.3

**Comment by TheNetsky** [comment]
Known, will not be fixed.
Just change the apostrophe by long holding the apostrophe on your keyboard.

**Comment by TheNetsky** [comment]
I'll take a look at that later.

**Comment by TheNetsky** [comment]
@btylerh7
