### ISSUE TITLE
NHentai Extension Source not working.

### ISSUE THREAD

**Issue by Batsy52** [TheNetsky/extensions-sources#4]
The NHentai source has been having problem with the cloudflare bypass. It is most probably an infinite cloudflare bypass issue. 
I have attached screenshots for reference.
![IMG_0054](https://user-images.githubusercontent.com/72062816/171985336-596e71e2-1dec-429c-b7f1-8cff27ac745d.PNG)
![IMG_0053](https://user-images.githubusercontent.com/72062816/171985338-6c143cbe-b782-4bf5-b049-96a3902f8e9c.PNG)

**Comment by TheNetsky** [comment]
Known issue, not much more we can do about that on our end.
Try a VPN etc.
