### ISSUE TITLE
nhentai broken

### ISSUE THREAD

**Issue by miIktoast** [TheNetsky/extensions-sources#45]
**Description**
Nhentai source doesn’t load any chapters in discovery page or library. Throws error when app loads, viewing source discovery page and source content from library

**Reproduce**
1. Open paperback
2. Select nhentai in discovery
3. No chapters load, throws error
4. Go to source settings, attempt cloudflare bypass 
5. Same result upon returning to discovery page

**App Version**
v0.7-r50

**Source Version**
nhentai 3.2.4

**Screenshots**
![378B7F6E-4FDE-4EAD-813A-90A6B6BC8316](https://user-images.githubusercontent.com/76277835/222226684-0e4cdf5a-f35a-462f-af77-1dfb99ec2fa7.png)
![ADA60D1F-B4EB-4117-90E3-875765250373](https://user-images.githubusercontent.com/76277835/222226690-e02c2895-fa65-4077-9738-8a3a19fe8cb5.jpeg)

**Comment by TheNetsky** [comment]
See: https://discord.com/channels/965890377896845352/965925084281847828/984425538988933160

**Comment by miIktoast** [comment]
Strange, I hadn’t set any tags, I even tested on a separate device with stock settings.

Though I did figure out that the ‘include all’ language option (defaulted on for me) was causing the error any prevented any chapters from appearing. 
When changing the option to a specific language source works as intended.

**Comment by TheNetsky** [comment]
I do not maintain that source, any issues regarding to it will not by fixed by me.
