### ISSUE TITLE
nHentai Cloudflare bypass not working

### ISSUE THREAD

**Issue by Starfall63** [TheNetsky/extensions-sources#49]
**Describe the bug**

When trying to do the cloudflare bypass it keeps getting stuck.

**To Reproduce**
1. Go to 'settings'
2. Click on 'nHentai '
3. Scroll down to 'Cloudflare bypass and click on it '

**Expected behavior**

Should be able to finish the Cloudflare bypass once the captcha is completed 

**Screenshots/Video**

https://user-images.githubusercontent.com/87585497/231527860-aacea46a-8ce5-4c48-8954-ea6b0891b06e.MOV

**App version**
- v0.7-r46

**Source WITH source version**
- nHentai 3.2.4

**Additional context**

**Comment by TheNetsky** [comment]
Known issue, however since no one is maintaining this source, not sure when this will be fixed.

**Comment by henderea** [comment]
@TheNetsky How are these issues usually fixed? If I know the process to follow, I might be able to submit a PR.

**Comment by xOnlyFadi** [comment]
> Just updating the user-agent which will work for a while until it gets blocked again. Source has to be remade for 0.8 and am not gonna not gonna.

probably the best way to make the agent to work everytime is to a the same agent with random numbers for safari or chrome

**Comment by TheNetsky** [comment]
> > Just updating the user-agent which will work for a while until it gets blocked again. Source has to be remade for 0.8 and am not gonna not gonna.
> 
> probably the best way to make the agent to work everytime is to a the same agent with random numbers for safari or chrome

If you save it in a state sure, other wise it's gonna be a cloudflare bypass for every launch or request.

**Comment by henderea** [comment]
When we say randomize the number, you mean the version number of the browser, right?

If I have the user agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15`, what part(s) would I be randomizing? 

And ya, I figured I'd randomize it at the start of the `getCloudflareBypassRequest` method and store it in the state.

**Comment by TheNetsky** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/78.0${Math.floor(Math.random() * 100000)}

**Comment by TheNetsky** [comment]
> When we say randomize the number, you mean the version number of the browser, right?
> 
> If I have the user agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15`, what part(s) would I be randomizing?
> 
> And ya, I figured I'd randomize it at the start of the `getCloudflareBypassRequest` method and store it in the state.
> 
> Though it doesn't look like that's async, so I probably can't block on the storage step

That was the whole issue, that's why it's async in 0.8

**Comment by TheNetsky** [comment]
You can try what I did with madara 0.6, with the user agents

**Comment by henderea** [comment]
Added pull request #50

**Comment by TheNetsky** [comment]
Tested?

**Comment by henderea** [comment]
@TheNetsky If you're asking if I've tested the pull request, I've tested the exact same code changes on a separate fork I maintain for personal use, so the code should work fine. The only differences in my personal fork are minor things that don't have anything to do with the cloudflare code.

**Comment by amurbain** [comment]
So, is this supposed to be working on `v0.7-r46`? My source updated to `3.2.5`, however is still exhibiting the same behavior as displayed in the video above.

**Comment by henderea** [comment]
@amurbain Make sure you go into content settings and generate a new user agent. It may take more than one attempt to get a user agent that works, but you should eventually get through. Make sure you "save" the press of the button; the display will update if you re-enter the content settings after saving.

**Comment by amurbain** [comment]
Ah, I see that now. Perfect. Thank you for clarifying.

**Comment by ariankordi** [comment]
Seemingly after this change and only after randomizing the user agent once, every time I reopen the app or reload the source, it can’t fetch the content. I have to open the Cloudflare Bypass and hit Done, even if it doesn’t even show a challenge, and then it’ll start showing it.

**Comment by TheNetsky** [comment]
Gotta refresh the homepage a couple of times after doing so.

**Comment by ariankordi** [comment]
I mean that after subsequent opens of the app, it prompts me for the error that requires me to do the bypass, every single time, even if there’s no actual challenge when I hit the bypass button. Then it works when I hit “done”.


I can provide a video or more steps if you need but this has happened to me on two different installations  on the app so far - just started on the second one only after using the randomize user agent feature for the first time. I’m not sure if this is specific to me though.

**Comment by henderea** [comment]
You should probably try randomizing another time or two until it starts working better. Not every random user agent will work well. And before this change, it wasn't working at all, so working only somewhat is still an improvement. 

Also, 0.7 isn't really supported anymore, so unless you submit a pull request yourself, it's unlikely for anything to get fixed. If re-randomizing the UA doesn't help, you'll just have to wait until you can upgrade to 0.8.

**Comment by ariankordi** [comment]
I see, I dug deeper and saw that the User-Agent header is being reset to the default every single time the app is opened (or source is reloaded), even though the cf_clearance cookie (which doesn't match the default user agent anymore since it was randomized......) IS being persisted and sent:
![image](https://github.com/TheNetsky/extensions-sources/assets/26663549/36cc48d7-00b7-4436-b4d8-055033d51106)

I'm probably going to look further into this myself. I'm wondering how to use the "Enable Debugger" feature in the Developer options, could you be so kind as to point me in the right direction for docs that show how to use this?



I'm also providing a video anyway. It pretty much just shows that, before randomizing the user agent, a fresh open will keep the Cloudflare bypass and then after randomization, every fresh open will require opening the bypass every single time.

https://github.com/TheNetsky/extensions-sources/assets/26663549/280ae526-e6d0-4dcd-aac4-0fe15010be76

**Comment by TheNetsky** [comment]
I am not going to fix this. Feel free to submit a PR if you're interested however.
