### ISSUE TITLE
Mangadex Search Issue

### ISSUE THREAD

**Issue by MFlynny86** [TheNetsky/extensions-sources#5]
When I was searching for a specific manga using Mangadex through Paperback, it doesn't come up but then it does come up when I search it on the website.
![image](https://user-images.githubusercontent.com/66037029/172527942-95cfeacc-f9c1-413d-9840-df8dc76d4b0e.png)
![image](https://user-images.githubusercontent.com/66037029/172527953-a337e4a7-888b-40be-85c0-d2b56a06750c.jpeg)

**Comment by xOnlyFadi** [comment]
You have not provided any useful information.

Missing:
App version
Source version

**Comment by MFlynny86** [comment]
v0.7-r46
MangaDex nar1n 2.1.8

**Comment by MFlynny86** [comment]
Nvm I figured it out, it was hidden in the content settings that it was filtered out, didn't think Akikan was that racy to be considered 'not safe' but 🤷‍♂️
