### ISSUE TITLE
[BUG] Specific manga can't be opened, JSError when parsing images

### ISSUE THREAD

**Issue by Pixelatex** [TheNetsky/extensions-sources#54]
**Describe the bug**

**To Reproduce**
1. Add the Readm extension
2. Try to open a chapter of the "Undead King ~ A low-Ranking adventurer,..." manga
3. See error

**Expected behavior**
Should open the chapter

**Screenshots/Video**

![IMG_69848E447525-1](https://github.com/TheNetsky/extensions-sources/assets/12593377/303d5665-bf90-4a26-ae69-04197b78d8a8)

**App version**
- v0.8-r61

**Source WITH source version**
- Readm 2.1.2

**Additional context**

This issue seems to be unique for this manga

**Comment by Pixelatex** [comment]
Same issue on Readm 2.1.6 still exists but only this specific manga as far as I can tell

**Comment by TheNetsky** [comment]
Works fine for me?

**Comment by Pixelatex** [comment]
Strange I still had the error but when I removed it from my library, it now finally works. Not sure what went wrong there
