### ISSUE TITLE
Asura scans not working

### ISSUE THREAD

**Issue by Sahibs1** [TheNetsky/extensions-sources#55]
Asurascans 2.1.14 is not working. Nothing will load. 
![IMG_0304](https://github.com/TheNetsky/extensions-sources/assets/108420410/2082d113-2c06-43a7-8ed8-7bc6e7a88cc6)

**Comment by TheNetsky** [comment]
Wrong repo and will not be fixed.

**Comment by TheNetsky** [comment]
1. The repo where u got it from, which is not this one.
2. Old 0.6 sources are no longer maintained.

**Comment by Sahibs1** [comment]
I got the repo from this discord, Netsky’s basement. It was from this section. 
![IMG_0306](https://github.com/TheNetsky/extensions-sources/assets/108420410/c29bf1df-4a6b-4d60-a30c-ad3d025b58be)

**Comment by TheNetsky** [comment]
Correct and this this not "extensions-mangastream", anyways case closed.

**Comment by Sahibs1** [comment]
So where would I go to do this properly next time?
