### ISSUE TITLE
Manga4life: 0.8 source?

### ISSUE THREAD

**Issue by Pixelatex** [TheNetsky/extensions-sources#56]
I noticed a lot of issues with the manga4life source and I was wondering if they are caused by it not being a 0.8 source yet.

Issues include:

* frequently stops working in search or updates 
* various manga have issues now and then and won't load
* library update for this source is very very slow

Are these issues that could be fixed with a 0.8 build and if so, is there any view on when this extension will be update to 0.8?

**Comment by TheNetsky** [comment]
The only reason why it hasn't been ported is because I have not had the time nor energy nor motivation to do so.

**Comment by Pixelatex** [comment]
Is there a way that others can help? Id be willing to take a look and try to fix it

**Comment by TheNetsky** [comment]
Everyone is free to do so. Also it's not broken, 0.8 will usually have big overhauls and improving them, this takes time.
