### ISSUE TITLE
[BUG] Sushi Scan doesn't work

### ISSUE THREAD

**Issue by Hidax517** [TheNetsky/extensions-sources#58]
**Describe the bug**
No mangas show on Sushi Scan

**To Reproduce**
1. Go to Sushi Scan
2. See Sushi Scan not loading

**Expected behavior**
Mangas should show

**Screenshots/Video**
![IMG_6670](https://github.com/TheNetsky/extensions-sources/assets/127059800/f4c04413-1cc5-4456-8cc9-83fe687db43c)

**App version**
- v0.8.2-r1

**Source WITH source version**
- Sushi Scan 3.0.0

**Comment by F4BB** [comment]
Click on The cloue on The top rigth validate cloue flare and enjoy, but, recently aides manga seems change URL and not load 

The new url seems : https://sushiscan.net/catalogue/ 
instead of : https://sushiscan.net/manga/

**Comment by TheNetsky** [comment]
Wrong repo
