### ISSUE TITLE
MangaDex forked source updating

### ISSUE THREAD

**Issue by Lyndis8** [TheNetsky/extensions-sources#9]
I can't seem to get the any of my series on the MangaDex source to update. If I check manually, I can find a new chapter, but the notification will not appear when I check for updates in all of my series at once. The notifications will not even appear even after I have opened the series manually to find a new chapter, which is what used to happen back on the TestFlight version.

The notifications will not appear on Paperback: v.07-r46, MangaDex: nar1n 2.1.8.

I also still haven't deleted my TestFlight app yet which is v0.7-r46, but the MangaDex updates work just fine on that one. Perhaps that might be interfering but I am unsure. 

This problem is only with MD and no other sources as far as I can tell.

**Comment by TheNetsky** [comment]
App issue, known.

**Comment by Lyndis8** [comment]
Oh sorry, didn't realize that. So it's something on Paperback's end? I am not sure how to downgrade the app version.

**Comment by TheNetsky** [comment]
It is on Paperback's end, however not sure which version caused this.

**Comment by Lyndis8** [comment]
Thanks for the quick responses. I hope they can fix whatever the issue is soon. Do I need to bring it up to them?

**Comment by TheNetsky** [comment]
Already known, fixed in 0.8.

**Comment by Lyndis8** [comment]
Gotcha, so I have to wait for the app store release of that. Thanks!
